---
- name: Deploy Kubernetes resources
  hosts: localhost
  connection: local
  become: yes  # Stay root, don't switch users
  vars:
    build_tag: "{{ lookup('env','BUILD_TAG') | default('latest') }}"
  roles:
    - k8s-deploy

- name: Update Prometheus config on master and node
  hosts: all
  become: yes
  vars:
    prometheus_config_path: /opt/prometheus/prometheus.yml
  tasks:
    - name: Template prometheus.yml with master and node IPs
      template:
        src:  /tmp/Insurance/ansible/roles/k8s-deploy/files/prometheus.yml.j2
        dest: "{{ prometheus_config_path }}"
        
        
        mode: '0644'
      vars:
        master_ip: "{{ master_ip }}"
        node_ip: "{{ node_ip }}"

   
